import {
  createField,
  createFormConfig,
  createSection,
} from '@/utils/form-builder';

export const statsFormConfig = createFormConfig({
  title: 'Estadísticas del Personaje',
  description:
    'Información básica, atributos, dominios y estadísticas de combate',
  sections: [
    createSection({
      title: 'Información Básica',
      columns: 2,
      fields: [
        createField('text', {
          name: 'playerName',
          label: 'Jugador',
          placeholder: 'Nombre del jugador',
          required: true,
          disabled: true,
        }),
        createField('text', {
          name: 'characterName',
          label: 'Nombre del personaje',
          placeholder: 'Introduce el nombre del personaje',
          required: true,
        }),
        createField('text', {
          name: 'archetype',
          label: 'Arquetipo',
          placeholder: 'Arquetipo del personaje',
          required: true,
        }),
        createField('text', {
          name: 'faction',
          label: 'Facción',
          placeholder: 'Facción del personaje',
          required: true,
        }),
        createField('text', {
          name: 'race',
          label: 'Raza',
          placeholder: 'Raza del personaje',
          required: true,
        }),
        createField('text', {
          name: 'category',
          label: 'Categoría',
          placeholder: 'Categoría del personaje',
          required: true,
        }),
        createField('number', {
          name: 'level',
          label: 'Nivel',
          placeholder: '1',
          required: true,
          min: 1,
          max: 20,
        }),
        createField('number', {
          name: 'epicPoints',
          label: 'Puntos de Épica (PÉP)',
          placeholder: '0',
          required: true,
          min: 0,
        }),
      ],
    }),
    createSection({
      title: 'Atributos',
      description: 'Valores de 1 a 100',
      columns: 3,
      fields: [
        createField('number', {
          name: 'strength',
          label: 'Fuerza (FUE)',
          required: true,
          min: 1,
          max: 100,
          defaultValue: 1,
        }),
        createField('number', {
          name: 'agility',
          label: 'Agilidad (DIN)',
          required: true,
          min: 1,
          max: 100,
          defaultValue: 1,
        }),
        createField('number', {
          name: 'willpower',
          label: 'Voluntad (VOL)',
          required: true,
          min: 1,
          max: 100,
          defaultValue: 1,
        }),
        createField('number', {
          name: 'luck',
          label: 'Suerte (SUR)',
          required: true,
          min: 1,
          max: 100,
          defaultValue: 1,
        }),
        createField('number', {
          name: 'intelligence',
          label: 'Inteligencia (INT)',
          required: true,
          min: 1,
          max: 100,
          defaultValue: 1,
        }),
      ],
    }),
    createSection({
      title: 'Dominios',
      description: 'Valores de 0 a 100',
      columns: 2,
      fields: [
        createField('number', {
          name: 'physical',
          label: 'Físico',
          min: 0,
          max: 100,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'combat',
          label: 'Batalla',
          min: 0,
          max: 100,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'social',
          label: 'Social',
          min: 0,
          max: 100,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'environmental',
          label: 'Ambiental',
          min: 0,
          max: 100,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'stealth',
          label: 'Sigilo',
          min: 0,
          max: 100,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'knowledge',
          label: 'Conocimiento',
          min: 0,
          max: 100,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'technical',
          label: 'Técnico',
          min: 0,
          max: 100,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'resources',
          label: 'Recursos',
          min: 0,
          max: 100,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'demonic',
          label: 'Demoníaco',
          min: 0,
          max: 100,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'aura',
          label: 'Aura',
          min: 0,
          max: 100,
          defaultValue: 0,
        }),
      ],
    }),
    createSection({
      title: 'Parámetros de Combate',
      columns: 2,
      fields: [
        createField('number', {
          name: 'physicalHealth',
          label: 'Salud física actual',
          required: true,
          min: 0,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'maxPhysicalHealth',
          label: 'Salud física máxima',
          required: true,
          min: 1,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'physicalResistance',
          label: 'Resistencia física actual',
          required: true,
          min: 0,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'maxPhysicalResistance',
          label: 'Resistencia física máxima',
          required: true,
          min: 0,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'mentalHealth',
          label: 'Salud mental actual',
          required: true,
          min: 0,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'maxMentalHealth',
          label: 'Salud mental máxima',
          required: true,
          min: 1,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'mentalResistance',
          label: 'Resistencia mental actual',
          required: true,
          min: 0,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'maxMentalResistance',
          label: 'Resistencia mental máxima',
          required: true,
          min: 0,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'initiative',
          label: 'Iniciativa',
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'defense',
          label: 'Defensa',
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'attack',
          label: 'Ataque',
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'impact',
          label: 'Impacto',
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'maxDamage',
          label: 'Daño máximo',
          min: 0,
          defaultValue: 0,
        }),
      ],
    }),
  ],
  submitButton: {
    text: 'Guardar Estadísticas',
    className: 'bg-blue-600 hover:bg-blue-700',
  },
});
