import {
  createField,
  createSection,
  type FormSectionConfig,
} from '@/utils/form-builder';

export const createStatsFormSections = (
  isEditMode: boolean
): FormSectionConfig[] => {
  return [
    createSection({
      title: 'Información Básica',
      description: 'Datos generales del personaje',
      columns: 2,
      fields: [
        createField('text', {
          name: 'playerName',
          label: 'Jugador',
          disabled: true, // Always disabled, read-only
          placeholder: 'Nombre del jugador',
        }),
        createField('text', {
          name: 'characterName',
          label: 'Nombre del Personaje',
          required: true,
          disabled: !isEditMode,
          placeholder: 'Nombre del personaje',
        }),
        createField('text', {
          name: 'archetype',
          label: 'Arquetipo',
          required: true,
          disabled: !isEditMode,
          placeholder: 'Arquetipo del personaje',
        }),
        createField('text', {
          name: 'faction',
          label: 'Facción',
          required: true,
          disabled: !isEditMode,
          placeholder: 'Facción del personaje',
        }),
        createField('text', {
          name: 'race',
          label: 'Raza',
          required: true,
          disabled: !isEditMode,
          placeholder: 'Raza del personaje',
        }),
        createField('text', {
          name: 'category',
          label: 'Categoría',
          disabled: !isEditMode,
          placeholder: 'Categoría (opcional)',
        }),
        createField('number', {
          name: 'level',
          label: 'Nivel',
          required: true,
          disabled: !isEditMode,
          min: 1,
          defaultValue: 1,
        }),
        createField('number', {
          name: 'epicPoints',
          label: 'Puntos Épicos',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
      ],
    }),

    createSection({
      title: 'Atributos',
      description: 'Atributos principales del personaje',
      columns: 3,
      fields: [
        createField('number', {
          name: 'strength',
          label: 'Fuerza',
          required: true,
          disabled: !isEditMode,
          min: 1,
          defaultValue: 1,
        }),
        createField('number', {
          name: 'agility',
          label: 'Agilidad',
          required: true,
          disabled: !isEditMode,
          min: 1,
          defaultValue: 1,
        }),
        createField('number', {
          name: 'willpower',
          label: 'Voluntad',
          required: true,
          disabled: !isEditMode,
          min: 1,
          defaultValue: 1,
        }),
        createField('number', {
          name: 'luck',
          label: 'Suerte',
          required: true,
          disabled: !isEditMode,
          min: 1,
          defaultValue: 1,
        }),
        createField('number', {
          name: 'intelligence',
          label: 'Inteligencia',
          required: true,
          disabled: !isEditMode,
          min: 1,
          defaultValue: 1,
        }),
      ],
    }),

    createSection({
      title: 'Dominios',
      description: 'Dominios de conocimiento y habilidad',
      columns: 3,
      fields: [
        createField('number', {
          name: 'physical',
          label: 'Físico',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'combat',
          label: 'Combate',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'social',
          label: 'Social',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'environmental',
          label: 'Ambiental',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'stealth',
          label: 'Sigilo',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'knowledge',
          label: 'Conocimiento',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'technical',
          label: 'Técnico',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'resources',
          label: 'Recursos',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'demonic',
          label: 'Demoníaco',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'aura',
          label: 'Aura',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
      ],
    }),

    createSection({
      title: 'Estadísticas de Combate',
      description: 'Salud, resistencia y estadísticas de combate',
      columns: 2,
      fields: [
        createField('number', {
          name: 'physicalHealth',
          label: 'Salud Física',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'maxPhysicalHealth',
          label: 'Salud Física Máxima',
          disabled: !isEditMode,
          min: 1,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'physicalResistance',
          label: 'Resistencia Física',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'maxPhysicalResistance',
          label: 'Resistencia Física Máxima',
          disabled: !isEditMode,
          min: 1,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'mentalHealth',
          label: 'Salud Mental',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'maxMentalHealth',
          label: 'Salud Mental Máxima',
          disabled: !isEditMode,
          min: 1,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'mentalResistance',
          label: 'Resistencia Mental',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'maxMentalResistance',
          label: 'Resistencia Mental Máxima',
          disabled: !isEditMode,
          min: 1,
          defaultValue: 100,
        }),
        createField('number', {
          name: 'initiative',
          label: 'Iniciativa',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'defense',
          label: 'Defensa',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'attack',
          label: 'Ataque',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'impact',
          label: 'Impacto',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
        createField('number', {
          name: 'maxDamage',
          label: 'Daño Máximo',
          disabled: !isEditMode,
          min: 0,
          defaultValue: 0,
        }),
      ],
    }),
  ];
};
