import {
  createField,
  createSection,
  type FormSectionConfig,
} from "@/utils/form-builder";
import { type FormMode, isFieldEditable } from "../types/form-mode";

export const createStatsFormSections = (
  mode: FormMode,
  users: Array<{ id: string; name: string; email: string }> = [],
): FormSectionConfig[] => {
  return [
    createSection({
      title: "Información Básica",
      description: "Datos generales del personaje",
      columns: 2,
      fields: [
        createField("select", {
          name: "userId",
          label: "Jugador",
          required: true,
          disabled: !isFieldEditable(mode),
          placeholder: "Selecciona un jugador",
          options: users.map((user) => ({
            value: user.id,
            label: `${user.name} (${user.email})`,
          })),
        }),
        createField("text", {
          name: "characterName",
          label: "Nombre del Personaje",
          required: true,
          disabled: !isFieldEditable(mode),
          placeholder: "Nombre del personaje",
        }),
        createField("text", {
          name: "archetype",
          label: "Arquetipo",
          required: true,
          disabled: !isFieldEditable(mode),
          placeholder: "Arquetipo del personaje",
        }),
        createField("text", {
          name: "faction",
          label: "Facción",
          required: true,
          disabled: !isFieldEditable(mode),
          placeholder: "Facción del personaje",
        }),
        createField("text", {
          name: "race",
          label: "Raza",
          required: true,
          disabled: !isFieldEditable(mode),
          placeholder: "Raza del personaje",
        }),
        createField("text", {
          name: "category",
          label: "Categoría",
          disabled: !isFieldEditable(mode),
          placeholder: "Categoría (opcional)",
        }),
        createField("number", {
          name: "level",
          label: "Nivel",
          required: true,
          disabled: !isFieldEditable(mode),
          min: 1,
          defaultValue: 1,
        }),
        createField("number", {
          name: "epicPoints",
          label: "Puntos Épicos",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
      ],
    }),

    createSection({
      title: "Atributos",
      description: "Atributos principales del personaje",
      columns: 3,
      fields: [
        createField("number", {
          name: "strength",
          label: "Fuerza",
          required: true,
          disabled: !isFieldEditable(mode),
          min: 1,
          defaultValue: 1,
        }),
        createField("number", {
          name: "agility",
          label: "Agilidad",
          required: true,
          disabled: !isFieldEditable(mode),
          min: 1,
          defaultValue: 1,
        }),
        createField("number", {
          name: "willpower",
          label: "Voluntad",
          required: true,
          disabled: !isFieldEditable(mode),
          min: 1,
          defaultValue: 1,
        }),
        createField("number", {
          name: "luck",
          label: "Suerte",
          required: true,
          disabled: !isFieldEditable(mode),
          min: 1,
          defaultValue: 1,
        }),
        createField("number", {
          name: "intelligence",
          label: "Inteligencia",
          required: true,
          disabled: !isFieldEditable(mode),
          min: 1,
          defaultValue: 1,
        }),
      ],
    }),

    createSection({
      title: "Dominios",
      description: "Dominios de conocimiento y habilidad",
      columns: 3,
      fields: [
        createField("number", {
          name: "physical",
          label: "Físico",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
        createField("number", {
          name: "combat",
          label: "Combate",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
        createField("number", {
          name: "social",
          label: "Social",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
        createField("number", {
          name: "environmental",
          label: "Ambiental",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
        createField("number", {
          name: "stealth",
          label: "Sigilo",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
        createField("number", {
          name: "knowledge",
          label: "Conocimiento",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
        createField("number", {
          name: "technical",
          label: "Técnico",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
        createField("number", {
          name: "resources",
          label: "Recursos",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
        createField("number", {
          name: "demonic",
          label: "Demoníaco",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
        createField("number", {
          name: "aura",
          label: "Aura",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
      ],
    }),

    createSection({
      title: "Estadísticas de Combate",
      description: "Salud, resistencia y estadísticas de combate",
      columns: 2,
      fields: [
        createField("number", {
          name: "physicalHealth",
          label: "Salud Física",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 100,
        }),
        createField("number", {
          name: "maxPhysicalHealth",
          label: "Salud Física Máxima",
          disabled: !isFieldEditable(mode),
          min: 1,
          defaultValue: 100,
        }),
        createField("number", {
          name: "physicalResistance",
          label: "Resistencia Física",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 100,
        }),
        createField("number", {
          name: "maxPhysicalResistance",
          label: "Resistencia Física Máxima",
          disabled: !isFieldEditable(mode),
          min: 1,
          defaultValue: 100,
        }),
        createField("number", {
          name: "mentalHealth",
          label: "Salud Mental",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 100,
        }),
        createField("number", {
          name: "maxMentalHealth",
          label: "Salud Mental Máxima",
          disabled: !isFieldEditable(mode),
          min: 1,
          defaultValue: 100,
        }),
        createField("number", {
          name: "mentalResistance",
          label: "Resistencia Mental",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 100,
        }),
        createField("number", {
          name: "maxMentalResistance",
          label: "Resistencia Mental Máxima",
          disabled: !isFieldEditable(mode),
          min: 1,
          defaultValue: 100,
        }),
        createField("number", {
          name: "initiative",
          label: "Iniciativa",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
        createField("number", {
          name: "defense",
          label: "Defensa",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
        createField("number", {
          name: "attack",
          label: "Ataque",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
        createField("number", {
          name: "impact",
          label: "Impacto",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
        createField("number", {
          name: "maxDamage",
          label: "Daño Máximo",
          disabled: !isFieldEditable(mode),
          min: 0,
          defaultValue: 0,
        }),
      ],
    }),
  ];
};
